# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28d5424d1d2e6eacdd345177087aa17e7434d3c904107c0c491079d834ec639766b97b7f42e80fd8b6e5fbd6d24f4e237630ff9b891580c4a4ba5a31b9d61ba3

test:
  secret_key_base: 3c1a8d1d7a1f75bb8e41c7c22251e2697be909279de78b9ce13b09d5bc8502ceceb19ba06ac3e5a42d71f1c28183cc04820c14ae8d0637d5089e64ffc2a18bb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
